version: "3.8"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  ldap:
    image: osixia/openldap:1.2.3
    volumes:
      - ./ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      - LDAP_ORGANISATION=cjavellana
      - LDAP_DOMAIN=cjavellana.me
      - LDAP_ADMIN_PASSWORD=secret
    ports:
      - 10389:389
      - 10636:636
    command: [--copy-service,  --loglevel, debug]
  web:
    build: .
    depends_on: 
      - db
      - ldap
    ports:
      - 8080:8080
    command: > 
      bash -c "airflow db upgrade
      && airflow webserver"
  scheduler:
    build: .
    depends_on: 
      - db
    command: > 
      bash -c "airflow db upgrade
      && airflow scheduler"
